baseURL = "https://auttogram.com.br"
languageCode = "pt"
DefaultContentLanguage = "pt"
title = "Auttogram"
theme = "auttogram"

[params]
  tagline = "Automação para Instagram"

[languages]
  [languages.pt]
    languageName = "Português"
    # baseURL = "https://gallant-thompson-129e79.netlify.com"
    title = "Auttogram em PT"

  [languages.en]
    languageName = "English"
    # baseURL = "https://youthful-curran-dfb0c3.netlify.com"
    title = "Auttogram em EN"
