baseURL = "http://brasilmaisdigital.com.br"
languageCode = "pt"
DefaultContentLanguage = "pt"
title = "Auttogram"
theme = "auttogram"

[params]
  tagline = "Automação para Instagram"

[languages]
  [languages.pt]
    languageName = "Português"
    baseURL = "http://pt.brasilmaisdigital.com.br"
    title = "Auttogram em PT"

  [languages.en]
    languageName = "English"
    baseURL = "http://en.brasilmaisdigital.com.br"
    title = "Auttogram em EN"
