baseURL = "http://gallant-thompson-129e79.netlify.com"
languageCode = "pt"
DefaultContentLanguage = "pt"
title = "Auttogram"
theme = "auttogram"

[params]
  tagline = "Automação para Instagram"

[languages]
  [languages.pt]
    languageName = "Português"
    baseURL = "http://gallant-thompson-129e79.netlify.com"
    title = "Auttogram em PT"

  [languages.en]
    languageName = "English"
    baseURL = "https://auttogram.com"
    title = "Auttogram em EN"
