[build]
publish = "public"
command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.41"

[redirects]
  from = "https://gallant-thompson-129e79.netlify.com/*"
  to = "https://gallant-thompson-129e79.netlify.com/pt/:splat 301!"
