[build]
publish = "public"
command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.41"

[[redirects]]
  from = "/"
  to = "/pt"
  status = 302
  conditions = { Language = ["pt"] }

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  conditions = { Language = ["en"] }
